# Generated by Django 4.2.2 on 2023-07-06 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_message_options_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='host_profilepic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.profile'),
        ),
    ]
