# Generated by Django 4.2.2 on 2023-07-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_room_host_profilepic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='host_profilepic',
        ),
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
